[package]
name = "pavenet-core"
version = "0.1.0"
edition = "2021"

[dependencies]
pavenet-engine = { version = "0.0.1", path = "../pavenet-engine" }
krabmaga = { version = "0.4.1", path= "../../krABMaga" }
hashbrown = "0.14.1"