[package]
name = "pavenet-core"
version = "0.0.1"
authors = [
    "Nagacharan Teja Tangirala <nagacharan.tangirala@tum.de>"
]
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
serde = "1.0.188"
serde_derive = "1.0.188"
hashbrown = "0.14.1"
toml = "0.8.1"
serde_with = "3.3.0"
typed-builder = "0.16.2"