[package]
name = "disolv-fl"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "disolv-fl"
path = "src/main.rs"

[dependencies]
disolv-core = { version = "0.0.0", path = "../../lib/disolv-core" }
disolv-input = { version = "0.0.0", path = "../../lib/disolv-input" }
disolv-output = { version = "0.0.0", path = "../../lib/disolv-output" }
disolv-models = { version = "0.0.0", path = "../../lib/disolv-models" }
disolv-runner = { version = "0.0.0", path = "../../lib/disolv-runner" }
burn = { workspace = true, features = ["wgpu", "train", "vision"] }
clap = { workspace = true, features = ["derive"] }
indexmap.workspace = true
log.workspace = true
log4rs.workspace = true
env_logger.workspace = true
typed-builder.workspace = true
serde = { workspace = true, features = ["derive"] }
rand.workspace = true
toml.workspace = true
uuid.workspace = true
hashbrown.workspace = true
ratatui.workspace = true
image.workspace = true
rusqlite.workspace = true
