[package]
name = "pavenet"
version = "0.0.1"
authors = [
    "Nagacharan Teja Tangirala <nagacharan.tangirala@tum.de>"
]
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
krabmaga = "0.4.1"
toml = "0.8.0"
serde = "1.0.188"
serde_derive = "1.0.188"
polars-core = "0.33.1"
polars-io = "0.33.1"
rand = "0.8.4"
log4rs = "1.2.0"
log = "0.4.20"
itertools = "0.11.0"
serde_with = "3.3.0"

[dependencies.polars]
version = "0.33.0"
features = ["parquet", "lazy", "performant"]

[features]
visualization = ["krabmaga/visualization"]
visualization_wasm = ["krabmaga/visualization_wasm"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
debug = true