[package]
name = "disolv-links"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disolv-links"
path = "src/main.rs"

[dependencies]
disolv-models = { path = "../../lib/disolv-models" }
disolv-core = { path = "../../lib/disolv-core" }
disolv-input = { path = "../../lib/disolv-input" }
disolv-output = { path = "../../lib/disolv-output" }
crossterm.workspace = true
ratatui.workspace = true
toml.workspace = true
kiddo.workspace = true
clap = { workspace = true, features = ["derive"] }
log.workspace = true
log4rs.workspace = true
serde = { workspace = true, features = ["derive"] }
chrono.workspace = true
parquet.workspace = true
arrow.workspace = true
hashbrown.workspace = true
