[package]
name = "disolv-links"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disolv-links"
path = "src/main.rs"

[dependencies]
disolv-models = { path = "../../lib/disolv-models" }
disolv-core = { path = "../../lib/disolv-core" }
disolv-input = { path = "../../lib/disolv-input" }
parquet = "53.3.0"
arrow = "53.3.0"
hashbrown = "0.15.2"
crossterm = "0.28.1"
ratatui = "0.28.1"
toml = "0.8.19"
kiddo = "4.2.1"
clap = { version = "4.5.22", features = ['derive'] }
log = "0.4.22"
log4rs = "1.3.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_with = "3.11.0"
