[package]
name = "disolv-links"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disolv-links"
path = "src/main.rs"

[dependencies]
disolv-models = { path = "../../lib/disolv-models" }
disolv-core = { path = "../../lib/disolv-core" }
disolv-input = { path = "../../lib/disolv-input" }
parquet = "52.1.0"
arrow = "52.1.0"
hashbrown = "0.14.5"
crossterm = "0.27.0"
ratatui = "0.26.1"
toml = "0.8.14"
kiddo = "4.2.0"
clap = { version = "4.5.9", features = ['derive'] }
log = "0.4.22"
log4rs = "1.3.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_with = "3.9.0"
