[package]
name = "pavenet-output"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
krabmaga = { version = "0.4.1", path= "../../krABMaga" }
