[package]
name = "disolv-output"
version = "0.0.0"
edition = "2021"

[dependencies]
disolv-core = { path = "../disolv-core" }
disolv-models = { path = "../disolv-models" }
serde = { version = "1.0.197", features = ["derive"] }
csv = "1.3.0"
typed-builder = "0.18.1"
log = "0.4.20"