[package]
name = "disolv-v2x"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "disolv-v2x"
path = "src/main.rs"

[dependencies]
disolv-core = { version = "0.0.0", path = "../../lib/disolv-core" }
disolv-input = { version = "0.0.0", path = "../../lib/disolv-input" }
disolv-output = { version = "0.0.0", path = "../../lib/disolv-output" }
disolv-models = { version = "0.0.0", path = "../../lib/disolv-models" }
disolv-runner = { version = "0.0.0", path = "../../lib/disolv-runner" }
toml.workspace = true
rand.workspace = true
indexmap.workspace = true
tikv-jemallocator.workspace = true
log4rs.workspace = true
log.workspace = true
itertools.workspace = true
clap = { workspace = true, features = ["derive"] }
typed-builder.workspace = true
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4"] }
hashbrown.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[dev-dependencies]
disolv-testutils = { path = "../../lib/disolv-testutils" }
