[package]
name = "disolv-v2x"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disolv-v2x"
path = "src/main.rs"

[dependencies]
disolv-core = { version = "0.0.0", path = "../../lib/disolv-core" }
disolv-input = { version = "0.0.0", path = "../../lib/disolv-input" }
disolv-output = { version = "0.0.0", path = "../../lib/disolv-output" }
disolv-models = { version = "0.0.0", path = "../../lib/disolv-models" }
toml = "0.8.14"
rand = "0.8.5"
indexmap = "2.2.6"
tikv-jemallocator = "0.6.0"
log4rs = "1.3.0"
log = "0.4.22"
itertools = "0.13.0"
clap = { version = "4.5.9", features = ["derive"] }
typed-builder = "0.19.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_with = "3.9.0"
ratatui = "0.26.3"
crossterm = "0.27.0"
parquet = "52.1.0"
arrow = "52.1.0"

[dev-dependencies]
disolv-testutils = { path = "../../lib/disolv-testutils" }