[package]
name = "disolv-fl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disolv-fl"
path = "src/main.rs"

[dependencies]
disolv-core = { version = "0.0.0", path = "../../lib/disolv-core" }
disolv-input = { version = "0.0.0", path = "../../lib/disolv-input" }
disolv-output = { version = "0.0.0", path = "../../lib/disolv-output" }
disolv-models = { version = "0.0.0", path = "../../lib/disolv-models" }
burn = {version = "0.13.2", features = ["wgpu", "train", "vision"]}
clap = { version = "4.5.9", features = ["derive"] }
indexmap = "2.2.6"
log = "0.4.22"
typed-builder = "0.19.1"
serde = { version = "1.0.204", features = ["derive"] }
