[package]
name = "pavenet-recipe"
version = "0.0.0"
edition = "2021"

[dependencies]
pavenet-core = { version="0.0.0", path = "../pavenet-core" }
pavenet-engine = { version="0.0.0", path = "../pavenet-engine" }
hashbrown = "0.14.1"
serde = "1.0.189"
serde_derive = "1.0.189"
typed-builder = "0.17.0"