[package]
name = "pavenet-input"
version = "0.0.1"
authors = [
    "Nagacharan Teja Tangirala <nagacharan.tangirala@tum.de>"
]
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
pavenet-core = { path = "../pavenet-core" }
pavenet-engine = { path = "../pavenet-engine" }
hashbrown = "0.14.1"
log = "0.4.20"
polars-core = "0.33.2"
polars-io = "0.33.2"
typed-builder = "0.16.2"

[dependencies.polars]
version = "0.33.2"
features = ["parquet", "lazy", "performant"]