[package]
name = "pavenet-engine"
version = "0.0.1"
authors = [
    "Nagacharan Teja Tangirala <nagacharan.tangirala@tum.de>"
]
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
pavenet-core = { version = "0.0.1", path= "../pavenet-core" }
krabmaga = { version = "0.4.1", path= "../../krABMaga" }
hashbrown = "0.14.1"
typed-builder = "0.16.2"
dyn-clone = "1.0.14"
downcast-rs = "1.2.0"

[features]
visualization = ["krabmaga/visualization"]