[package]
name = "disolv-models"
version = "0.0.0"
edition = "2021"

[dependencies]
disolv-core = { path = "../disolv-core" }
serde = { version = "1.0.197", features = ["derive"] }
typed-builder = "0.18.1"
rand_distr = "0.4.3"
log = "0.4.21"
rand = "0.8.5"
rand_pcg = "0.3.1"
serde_with = "3.6.1"

