# The run config is used for both run mode and debug mode

[[configs]]
name = "disolv"

# the type of the debugger. If not set, it can't be debugged but can still be run
# type = "lldb"

# the program to run
program = "target/release/disolv"

# the program arguments, e.g. args = ["arg1", "arg2"], optional
args = ["--config", "/mnt/hdd/workspace/disolv/configs/lehen100/disolv.toml"]

# current working directory, optional
# cwd = "${workspace}"

# enviroment variables, optional
# [configs.env]
# VAR1 = "VAL1"
# VAR2 = "VAL2"

# task to run before the run/debug session is started, optional
[configs.prelaunch]
program = "cargo"
args = [
  "build", "--package", "disolv", "--release"
]
